title: "Thoughts on money"
email: 
timezone: UTC
baseurl: "/affiliates-jekyll-theme"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: R
paginate: 10
disqus:
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: weekly
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics:

# Authors
authors:
  ruan:
    name: Ruan
    display_name: R
    avatar: 'assets/images/sal.png'
    email: 
    web:
    twitter: 
    description: "Writing about money."

# Social
social:
  instagram: 
  facebook: 
  twitter: 

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
